apiVersion: v1
kind: pod
metadata:
  name: clien-pod
  lables:
    component: web
spec:
  containers:
    - name: client
      image: stephengrider/multi-client
      ports:
        - containerPort: 3000
